mysite/blog/urls.py
from django.urls import path
from . import views
app_name='blog'

urlpatterns=[
    #Post Views
    
    
    path('',views.post_list,name='post_list'),
    
    # Class Based View
    # path('', views.PostListView.as_view(), name='post_list'),
    
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    
    # path('<int:id>/',views.post_detail, name='post_detail')
    #SEO Friendly URL Genration in form of  /blog/2022/1/1/who-was-django-reinhardt/.
    path('<int:year>/<int:month>/<int:day>/<slug:post>',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('<int:post_id>/comment/',views.post_comment, name='post_comment')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog'))
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)
# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    #Third Party Software The tags manager will allow you to add, retrieve, and remove tags from Post objects.
    tags=TaggableManager()

    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=200,unique_for_date='publish')
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body=models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,choices=Status.choices,default=Status.DRAFT)

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.   
    # We have added a Meta class inside the model. This class defines metadata for the model. We use the
    # ordering attribute to tell Django that it should sort results by the publish field. This ordering will
    # apply by default for database queries when no specific order is provided in the query. We indicate
    # descending order by using a hyphen before the field name, -publish. Posts will be returned in reverse
    # chronological order by default.
    class Meta:
        ordering = ['-publish']


        # We have added the indexes option to the model’s Meta class. This option allows you to define database
        # indexes for your model, which could comprise one or multiple fields, in ascending or descending
        # order, or functional expressions and database functions. We have added an index for the publish
        # field. We use a hyphen before the field name to define the index in descending order. The creation of
        # this index will be included in the database migrations that we will generate later for our blog models.
        indexes = [
            models.Index(fields=['-publish']),
        ]

    
    
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        # return reverse('blog:post_detail',args=[self.id])
        return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day,self. slug])

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ['created']
        indexes = [
        models.Index(fields=['created']),
        ]
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields  = ['name', 'email', 'body']

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import  Http404
from .models import Post,Comment
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count

# Create your views here.
def post_list(request,tag_slug=None):
    # posts=Post.published.all()
    post_list=Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        print(f'tag_{tag}')
        print(f'tag_{tag.__dict__}')
        post_list = post_list.filter(tags__in=[tag])
        
    paginator=Paginator(post_list,2)
    page_number=request.GET.get('page',1)
    # posts=paginator.page(page_number)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    context={
        'posts':posts,
        'tag': tag
    }
    return render(request,template_name='blog/post/list.html',context=context)


# def post_detail(request, id):
#     # try:
#     #     post = Post.published.get(id=id)
#     # except Post.DoesNotExist:
#     #     raise Http404("No Post found.")
#     post = get_object_or_404(Post,id=id,status=Post.Status.PUBLISHED)
#     context={'post': post}
#     return render(request,'blog/post/detail.html',context=context)

#SEO Friendly URL Genration in form of  /blog/2022/1/1/who-was-django-reinhardt/
def post_detail(request, year, month, day,post ):
    post = get_object_or_404(Post,status=Post.Status.PUBLISHED,slug=post,publish__year=year,publish__month=month,publish__day=day)
    # List of active comments for this post
    comments=post.comments.filter(active=True)
    # Form for users to comment

    tags=post.tags.all().values()
    print(f'tags_{tags}')
    
    tags_list=post.tags.all().values_list()
    print(f'tags_list_{tags_list}')

    post_tags_ids = post.tags.values_list('id', flat=True)
    print(f'post_tags_ids_{post_tags_ids}')
    
    print(f'post_   {post.id}')

    similar_posts=Post.published.filter(tags__in=post.tags.all()).exclude(id=post.id)
    print(f'similar_posts_{similar_posts}')
    print(f'similar_posts_query_{similar_posts.query}')

    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    print(f'similar_posts_{similar_posts.values()}')
    # print(f'similar_posts_query_{similar_posts.query}')

    form=CommentForm()
    context={'post': post,'comments': comments,'form': form,'similar_posts':similar_posts}
    return render(request,'blog/post/detail.html',context=context)

#class Based View for post_list view function written above
class PostListView(ListView):
    """
    Alternative post list view
    """

    # model=Post
    queryset = Post.published.all()
    #We use queryset to use a custom QuerySet instead of retrieving all objects. Instead of defining a queryset attribute, we could have specified model = Post and Django would have built the generic Post.objects.all() QuerySet for us.
    
    
    #We use the context variable posts for the query results. The default variable is object_list if you don’t specify any context_object_name.
    context_object_name = 'posts'

    #We define the pagination of results with paginate_by, returning three objects per page.
    paginate_by = 2

    #We use a custom template to render the page with template_name. If you don’t set a default template, ListView will use blog/post_list.html by default.
    template_name = 'blog/post/list.html'

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    form = EmailPostForm()
    # print(f'form_{form}')
    sent=False
    if request.method == 'POST':
    # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
        # Form fields passed validation
            cleaned_data = form.cleaned_data
            print(f'cleaned_data_{cleaned_data}')
            post_url = request.build_absolute_uri(
            post.get_absolute_url())
            print(f'absolute_url_{post.get_absolute_url()}')
            print(f'post_url_{post_url}')

            subject = f"{cleaned_data['name']} recommends you read " \
            f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
            f"{cleaned_data['name']}\'s comments: {cleaned_data['comments']}"
            mail_output=send_mail(subject, message, 'sachindahda.escalon@gmail.com',
            [cleaned_data['to']])
            print(f'mail_output_{mail_output}')
            sent = True
        # ... send email
    return render(request, 'blog/post/share.html', {'post': post,
    'form': form,'sent': sent})

@require_POST
def post_comment(request,post_id):
    post=get_object_or_404(Post,id=post_id,status=Post.Status.PUBLISHED)
    Comment=None
    #A comment was posted
    form=CommentForm(request.POST)
    print(f'form_{form}')
    if form.is_valid():
        comment=form.save(commit=False)

        # Assign the post to the comment
        comment.post=post
        # Save the comment to the database
        comment.save()
        print(f'comment_{comment}')
    return render(request, 'blog/post/comment.html',{'post': post,'form': form,'comment': comment})

mysite/blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}
{% block title %}
  Add a comment
{% endblock %}
{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p>
      <a href="{{ post.get_absolute_url }}">Back to the post</a>
    </p>
  {% else %}
    {% include 'blog/post/includes/comment_form.html' %}
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
  Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
  <a href="{% url "blog:post_share" post.id %}">
    Share this post
  </a>
  <h2>Similar posts</h2>
  </p>
  {% for single_related_post in similar_posts %}
    <p>
      <a href="{{ single_related_post.get_absolute_url }}">{{single_related_post.title}}</a>
    </p>
  {% empty %} 
    There are no similar posts
  {% endfor %}
  {% with comments.count as total_comments %}
    <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>There are no comments.</p>
  {% endfor %}

  {% include 'blog/post/includes/comment_form.html'%}
{% endblock %}

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
     <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <!-- <a href=" url 'blog:post_detail' post.id "> -->
            <!-- Canonical Url get_absolute_url which is retrieving values from method get_absolute_url overriden in post model  -->
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
            
        </h2>
        {% comment %} <p class="tags">Tags: {{ post.tags.all|join:", " }}</p> {% endcomment %}
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    
    {% comment %} {% include "pagination.html" with page=posts %} {% endcomment %}

    {% comment %} we have to use the right page object that is passed to the template. Django’s ListView generic view passes the page requested in a variable called page_obj. {% endcomment %}
    {% comment %} {% include "pagination.html" with page=page_obj %}  {% endcomment %}

    {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post" novalidate>
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}